services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    ports:
      - "5001:5000"
    command: mlflow server --backend-store-uri postgresql+psycopg2://admin:admin@postgres:5432/mlflow --default-artifact-root ./mlruns --host 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true